baseURL = "http://example.org/"
languageCode = "fr"
title = "My New Hugo Site"
defaultContentLanguage = "fr"

[languages]
  [languages.fr]
    title = "Mon Site Hugo avec i18n"
    languageName = "Français"
    weight = 1
  [languages.en]
    title = "My new Hugo Site with i18n"
    languageName = "English"
    weight = 2
